import pandas as pd
from tkinter import *
from tkinter import ttk
from tkinter.scrolledtext import ScrolledText
import yaml
from yaml_test_recipe import add_recipe,random_recipe,recipe_search,show_Cookbook,show_TOC
from yaml_test_recipe import change_plan,clear_DOWMeal_ALL,grocery_list,set_DOWMeal_Random

def openTOC():      
    Rec_text.delete("1.0","end")
    start_Label_string.set('Table of Contents')
    for i in show_TOC():
        Rec_text.insert(INSERT,(i) + '\n')

def full_cookbook():     
    Rec_text.delete("1.0","end")
    start_Label_string.set('Cookbook')
    for i in show_Cookbook():
        Rec_text.insert(INSERT, i[0])
        Rec_text.insert(INSERT, '\n--------------------------\n')        
        for x in i[1]:
            Rec_text.insert(INSERT,'\t')
            Rec_text.insert(INSERT,x[0])
            Rec_text.insert(INSERT,' ')
            Rec_text.insert(INSERT,x[1])
            Rec_text.insert(INSERT,' ')
            Rec_text.insert(INSERT,x[2])
            Rec_text.insert(INSERT,'\n')
        Rec_text.insert(INSERT, i[2])
        Rec_text.insert(INSERT, '\n--------------------------\n')
        Rec_text.insert(INSERT, '--------------------------\n')

def rand_rec():
    Rec_text.delete("1.0","end")
    start_Label_string.set('Random Recipe') 
    y = random_recipe()
    Rec_text.insert(INSERT, y[0])
    Rec_text.insert(INSERT, '\n--------------------------\n')
    for i in y[1]:
            Rec_text.insert(INSERT,'\t')
            Rec_text.insert(INSERT,i[0])
            Rec_text.insert(INSERT,' ')
            Rec_text.insert(INSERT,i[1])
            Rec_text.insert(INSERT,' ')
            Rec_text.insert(INSERT,i[2])
            Rec_text.insert(INSERT,'\n')
    Rec_text.insert(INSERT, '--------------------------\n')
    Rec_text.insert(INSERT, y[2]) 
    Rec_text.insert(INSERT, '\n\n')

def view_plan():
    clr_plan_display()
    with open('weeklymealplan.yaml','r') as file:        
        dow_dict = yaml.safe_load(file)       
        df = pd.DataFrame.from_dict(dow_dict)
        meal_order = ['Breakfast','Lunch','Dinner']
        df = df.sort_index(ascending=True)
        df = df.reindex(meal_order)        

        mon_din.insert(INSERT,df['Monday']['Dinner'])
        tue_din.insert(INSERT,df['Tuesday']['Dinner'])
        wed_din.insert(INSERT,df['Wednesday']['Dinner'])
        thu_din.insert(INSERT,df['Thursday']['Dinner'])
        fri_din.insert(INSERT,df['Friday']['Dinner'])
        sat_din.insert(INSERT,df['Saturday']['Dinner'])
        sun_din.insert(INSERT,df['Sunday']['Dinner'])
        mon_break.insert(INSERT,df['Monday']['Breakfast'])
        tue_break.insert(INSERT,df['Tuesday']['Breakfast'])
        wed_break.insert(INSERT,df['Wednesday']['Breakfast'])
        thu_break.insert(INSERT,df['Thursday']['Breakfast'])
        fri_break.insert(INSERT,df['Friday']['Breakfast'])
        sat_break.insert(INSERT,df['Saturday']['Breakfast'])
        sun_break.insert(INSERT,df['Sunday']['Breakfast'])        
        mon_lun.insert(INSERT,df['Monday']['Lunch'])
        tue_lun.insert(INSERT,df['Tuesday']['Lunch'])
        wed_lun.insert(INSERT,df['Wednesday']['Lunch'])
        thu_lun.insert(INSERT,df['Thursday']['Lunch'])
        fri_lun.insert(INSERT,df['Friday']['Lunch'])
        sat_lun.insert(INSERT,df['Saturday']['Lunch'])
        sun_lun.insert(INSERT,df['Sunday']['Lunch'])

def rand_plan():
    set_DOWMeal_Random() 
    view_plan()

def clr_plan_display():
    mon_din.delete("1.0","end")
    tue_din.delete("1.0","end")
    wed_din.delete("1.0","end")
    thu_din.delete("1.0","end")
    fri_din.delete("1.0","end")
    sat_din.delete("1.0","end")
    sun_din.delete("1.0","end")
    mon_break.delete("1.0","end")
    tue_break.delete("1.0","end")
    wed_break.delete("1.0","end")
    thu_break.delete("1.0","end")
    fri_break.delete("1.0","end")
    sat_break.delete("1.0","end")
    sun_break.delete("1.0","end")
    mon_lun.delete("1.0","end")
    tue_lun.delete("1.0","end")
    wed_lun.delete("1.0","end")
    thu_lun.delete("1.0","end")
    fri_lun.delete("1.0","end")
    sat_lun.delete("1.0","end")
    sun_lun.delete("1.0","end")
    
def clr_plan():
    clear_DOWMeal_ALL()
    clr_plan_display()

def groc_list():
    groclist_list.delete("1.0","end")
    for i in grocery_list():
        for y in i:
            groclist_list.insert(INSERT,str(y[0]))
            groclist_list.insert(INSERT,', ')
            groclist_list.insert(INSERT,str(y[2]))
            groclist_list.insert(INSERT,' ')
            groclist_list.insert(INSERT,str(y[1]))
            groclist_list.insert(INSERT,'\n')

def chg_plan():    
    day_dict = {1:'Monday', 2:'Tuesday', 3:'Wednesday', 4:'Thursday', 5:'Friday', 6:'Saturday', 7:'Sunday'}
    meal_dict = {1:'Breakfast',2:'Lunch',3:'Dinner'}    
    day_to_change = day_dict[var.get()] 
    meal_to_change = meal_dict[var2.get()]
    rec_to_add = current_var.get()
    change_plan(day_to_change,meal_to_change,rec_to_add)
    view_plan()

def show_top():
    top_chngmeal.grid(row=2,column=1,sticky=N)
    R1_Meal = Radiobutton(frm_mealbutts, text="Breakfast", variable=var2, value=1)
    R2_Meal = Radiobutton(frm_mealbutts, text="Lunch", variable=var2, value=2)
    R3_Meal = Radiobutton(frm_mealbutts, text="Dinner", variable=var2, value=3)
    R1_Meal.grid(column=1,row=1,sticky=W)
    R2_Meal.grid(column=1,row=2,sticky=W)
    R3_Meal.grid(column=1,row=3,sticky=W)
    R1_DOW = Radiobutton(frm_dowbutts, text="Monday", variable=var, value=1)
    R2_DOW = Radiobutton(frm_dowbutts, text="Tuesday", variable=var, value=2)
    R3_DOW = Radiobutton(frm_dowbutts, text="Wednesday", variable=var, value=3)
    R4_DOW = Radiobutton(frm_dowbutts, text="Thursday", variable=var, value=4)
    R5_DOW = Radiobutton(frm_dowbutts, text="Friday", variable=var, value=5)
    R6_DOW = Radiobutton(frm_dowbutts, text="Saturday", variable=var, value=6)
    R7_DOW = Radiobutton(frm_dowbutts, text="Sunday", variable=var, value=7)
    R1_DOW.grid(column=1,row=1,sticky=W)
    R2_DOW.grid(column=1,row=2,sticky=W)
    R3_DOW.grid(column=1,row=3,sticky=W)
    R4_DOW.grid(column=1,row=4,sticky=W)
    R5_DOW.grid(column=2,row=1,sticky=W)
    R6_DOW.grid(column=2,row=2,sticky=W)
    R7_DOW.grid(column=2,row=3,sticky=W)
    rec_combobox = ttk.Combobox(top_chngmeal,textvariable=current_var,state='readonly',values=toc_values)
    rec_combobox.grid(row=4)
    savechng_button = ttk.Button(top_chngmeal, text='Save',command=chg_plan,width=button_width)
    savechng_button.grid(row=20)

def view_rec():
    Rec_text.delete("1.0","end")
    start_Label_string.set('View Recipe')
    search_text = current_var_view.get()
    try:
        y = recipe_search(search_text)    
        Rec_text.insert(INSERT, y[0])
        Rec_text.insert(INSERT, '\n--------------------------\n')    
        for i in y[1]:
                Rec_text.insert(INSERT,'\t')
                Rec_text.insert(INSERT,i[0])
                Rec_text.insert(INSERT,' ')
                Rec_text.insert(INSERT,i[1])
                Rec_text.insert(INSERT,' ')
                Rec_text.insert(INSERT,i[2])
                Rec_text.insert(INSERT,'\n')
        Rec_text.insert(INSERT, '--------------------------\n')
        Rec_text.insert(INSERT, y[2]) 
        Rec_text.insert(INSERT, '\n\n')
    except:
      Rec_text.insert(INSERT, 'Select a recipe first!')  
    
def add_recWin():
    def add_ing_to_list():
        x = Entry_string_ingname.get()
        y = Entry_string_uom.get()
        z = Entry_string_qty.get()
        tuple_list[x]={y:float(z)}
        inglist_entry.insert(INSERT,x)
        inglist_entry.insert(INSERT,', ')
        inglist_entry.insert(INSERT,z)
        inglist_entry.insert(INSERT,' ')
        inglist_entry.insert(INSERT,y)
        inglist_entry.insert(INSERT,'\n')
        x = Entry_string_ingname.set('')
        y = Entry_string_uom.set('')
        z = Entry_string_qty.set('')

    def add_rec():    
        recipe_name = Entry_string_name.get()
        instructions_full = instruction_entry.get("1.0", "end-1c") 
        add_recipe(recipe_name,tuple_list,instructions_full)        
        recipe_name = Entry_string_name.set('')        
        top_add.destroy()
        top_add.update()
        
    global tuple_list    
    tuple_list = {}
    top_add = Toplevel()
    top_add.title('Add New Recipe')
    name_entry = ttk.Entry(top_add,textvariable=Entry_string_name)
    instruction_entry = Text(top_add,width=35,height=6)
    ingname_entry = ttk.Entry(top_add,textvariable=Entry_string_ingname)
    uom_entry = ttk.Entry(top_add,textvariable=Entry_string_uom)
    qty_entry = ttk.Entry(top_add,textvariable=Entry_string_qty,width=8)
    inglist_entry = Text(top_add,width=30,height=6)
    name_entry.grid(row=1,column=1,sticky=W,columnspan=3)    
    ingname_entry.grid(row=3,column=1,sticky=W)
    uom_entry.grid(row=3,column=2,sticky=W)
    qty_entry.grid(row=3,column=3,sticky=W)
    inglist_entry.grid(row=4,column=1,sticky=W,columnspan=3)
    instruction_entry.grid(row=8,column=1,sticky=W,columnspan=3)
    instruction_labl = ttk.Label(top_add,text='Instructions')
    ingname_labl = ttk.Label(top_add,text='Ingredient')
    uom_labl = ttk.Label(top_add,text='UOM')
    qty_labl = ttk.Label(top_add,text='QTY')        
    ingname_labl.grid(row=2,column=1,sticky=W)
    uom_labl.grid(row=2,column=2,sticky=W)
    qty_labl.grid(row=2,column=3,sticky=W)
    instruction_labl.grid(row=7,column=1,sticky=W)
    adding_button = ttk.Button(top_add, text='+',command=add_ing_to_list,width=3)
    adding_button.grid(row=3,column=4)    
    addrec_button = ttk.Button(top_add, text='Save',command=add_rec,width=button_width)
    addrec_button.grid(row=10,column=2)        
    
#Root
####################################################################
root = Tk()
root.title('Meal Planner')
frm_tabs = ttk.Frame(root, padding=10,relief=GROOVE)
frm_tabs.grid(row=1,column=0,rowspan=5)
tabControl = ttk.Notebook(frm_tabs)
tabControl.grid(row=1,column=0)

#Static Variables
#################################################################### 
button_width = 20
start_Label_string = StringVar()
Entry_string_name = StringVar()
Entry_string_instr = StringVar()
Entry_string_ingname = StringVar()
Entry_string_uom = StringVar()
Entry_string_qty = StringVar()
var = IntVar()
var2 = IntVar()
current_var = StringVar()
current_var_view = StringVar()
toc_values = []
for i in show_TOC():
    toc_values.append(i)
    toc_values = sorted(toc_values)

#Cookbook
####################################################################
tab_recipes = ttk.Frame(tabControl, padding=10,relief=GROOVE)
tab_recipes.grid(row=1,column=1)
frm_TOC = ttk.Frame(tab_recipes, padding=10,relief=GROOVE)
frm_TOC.grid(row=1,column=2,rowspan=5)
frm_recbuttons = ttk.Frame(tab_recipes, padding=10,relief=GROOVE)
frm_recbuttons.grid(row=1,column=1,rowspan=5,sticky=N)
frm_recbuttlist = ttk.Frame(frm_recbuttons, padding=10,relief=GROOVE)
frm_recbuttlist.grid(row=1,column=1,sticky=N)
frm_recview = ttk.Frame(frm_recbuttons, padding=10,relief=GROOVE)
frm_recview.grid(row=2,column=1,sticky=N)
frm_surprise = ttk.Frame(frm_recbuttons, padding=10,relief=GROOVE)
frm_surprise.grid(row=3,column=1,sticky=N)
Rec_text = ScrolledText(frm_TOC)
Rec_text.grid(row=1,column=3,rowspan=4)
start_Label_string.set('Make a Selection on the Right')
start_Label = ttk.Label(frm_TOC,textvariable=start_Label_string)
start_Label.grid(row=0,column=3,sticky=NW)
toc_button = ttk.Button(frm_recbuttlist, text='Table of Contents',command=openTOC,width=button_width)
toc_button.grid(row=1,column=1)
cookbook_button = ttk.Button(frm_recbuttlist, text='Cookbook',command=full_cookbook,width=button_width)
cookbook_button.grid(row=2,column=1)
open_button = ttk.Button(frm_recbuttlist, text='Add Recipe',command=add_recWin,width=button_width)
open_button.grid(row=5,column=1)
recname_combobox = ttk.Combobox(frm_recview,textvariable=current_var_view,state='readonly',values=toc_values)
recname_combobox.grid(column=1)
search_button = ttk.Button(frm_recview, text='View Recipe',command=view_rec,width=button_width)
search_button.grid(column=1)
random_button = ttk.Button(frm_surprise, text='Surprise Me',command=rand_rec,width=button_width)
random_button.grid(row=3,column=1)

#Meal Plan
####################################################################
tab_meal = ttk.Frame(tabControl, padding=10,relief=GROOVE)
tab_meal.grid(row=2,column=1)
frm_mealbuttons = ttk.Frame(tab_meal, padding=10,relief=GROOVE)
frm_mealbuttons.grid(row=1,column=1,sticky=N)
frm_mealbutt_start = ttk.Frame(frm_mealbuttons, padding=10,relief=GROOVE)
frm_mealbutt_start.grid(row=1,column=1,sticky=N)
frm_meal = ttk.Frame(tab_meal, padding=10,relief=GROOVE)
frm_meal.grid(row=1,column=2)
top_chngmeal = ttk.Frame(frm_mealbuttons, padding=10,relief=GROOVE)
frm_dowbutts = ttk.Frame(top_chngmeal, padding=10,relief=GROOVE)
frm_dowbutts.grid(row=1)
frm_mealbutts = ttk.Frame(top_chngmeal, padding=10,relief=GROOVE)
frm_mealbutts.grid(row=2)
mon_label = ttk.Label(frm_meal,text="Mon")
tue_label = ttk.Label(frm_meal,text="Tue")
wed_label = ttk.Label(frm_meal,text="Wed")
thu_label = ttk.Label(frm_meal,text="Thu")
fri_label = ttk.Label(frm_meal,text="Fri")
sat_label = ttk.Label(frm_meal,text="Sat")
sun_label = ttk.Label(frm_meal,text="Sun")
mon_label.grid(row=1,column=1) 
tue_label.grid(row=1,column=2)
wed_label.grid(row=1,column=3)
thu_label.grid(row=1,column=4) 
fri_label.grid(row=1,column=5) 
sat_label.grid(row=1,column=6) 
sun_label.grid(row=1,column=7)
dinner_label = ttk.Label(frm_meal,text="Dinner")
dinner_label.grid(row=4,column=0,sticky=N)
mon_din = Text(frm_meal,width=10,height=5)
tue_din = Text(frm_meal,width=10,height=5)
wed_din = Text(frm_meal,width=10,height=5)
thu_din = Text(frm_meal,width=10,height=5)
fri_din = Text(frm_meal,width=10,height=5)
sat_din = Text(frm_meal,width=10,height=5)
sun_din = Text(frm_meal,width=10,height=5)
mon_din.grid(row=4,column=1)
tue_din.grid(row=4,column=2)
wed_din.grid(row=4,column=3)
thu_din.grid(row=4,column=4)
fri_din.grid(row=4,column=5)
sat_din.grid(row=4,column=6)
sun_din.grid(row=4,column=7)
lunch_label = ttk.Label(frm_meal,text="Lunch")
lunch_label.grid(row=3,column=0,sticky=N)
mon_lun = Text(frm_meal,width=10,height=5)
tue_lun = Text(frm_meal,width=10,height=5)
wed_lun = Text(frm_meal,width=10,height=5)
thu_lun = Text(frm_meal,width=10,height=5)
fri_lun = Text(frm_meal,width=10,height=5)
sat_lun = Text(frm_meal,width=10,height=5)
sun_lun = Text(frm_meal,width=10,height=5)
mon_lun.grid(row=3,column=1)
tue_lun.grid(row=3,column=2)
wed_lun.grid(row=3,column=3)
thu_lun.grid(row=3,column=4)
fri_lun.grid(row=3,column=5)
sat_lun.grid(row=3,column=6)
sun_lun.grid(row=3,column=7)
breakfast_label = ttk.Label(frm_meal,text="Breakfast")
breakfast_label.grid(row=2,column=0,sticky=N)
mon_break = Text(frm_meal,width=10,height=5)
tue_break = Text(frm_meal,width=10,height=5)
wed_break = Text(frm_meal,width=10,height=5)
thu_break = Text(frm_meal,width=10,height=5)
fri_break = Text(frm_meal,width=10,height=5)
sat_break = Text(frm_meal,width=10,height=5)
sun_break = Text(frm_meal,width=10,height=5)
mon_break.grid(row=2,column=1)
tue_break.grid(row=2,column=2)
wed_break.grid(row=2,column=3)
thu_break.grid(row=2,column=4)
fri_break.grid(row=2,column=5)
sat_break.grid(row=2,column=6)
sun_break.grid(row=2,column=7)
view_plan_button = ttk.Button(frm_mealbutt_start, text='View Current Plan',command=view_plan,width=button_width)
view_plan_button.grid()
plan_button = ttk.Button(frm_mealbutt_start, text='Gen MWF Dinner Plan',command=rand_plan,width=button_width)
plan_button.grid()
clearplan_button = ttk.Button(frm_mealbutt_start, text='Clear Meal Plan',command=clr_plan,width=button_width)
clearplan_button.grid()
setmeal_button = ttk.Button(frm_mealbutt_start, text='Set Meal',command=show_top,width=button_width)
setmeal_button.grid()

#Grocery List
####################################################################
tab_grocery = ttk.Frame(tabControl, padding=10,relief=GROOVE)
tab_grocery.grid(row=3,column=1)
frm_grocbuttons = ttk.Frame(tab_grocery, padding=10,relief=GROOVE)
frm_grocbuttons.grid(column=1,row=1,sticky=N)
frm_groc = ttk.Frame(tab_grocery, padding=10,relief=GROOVE)
frm_groc.grid(column=2,row=1)
groclist_button = ttk.Button(frm_grocbuttons, text='Grocery List',command=groc_list,width=button_width)
groclist_button.grid()
groclist_list = ScrolledText(frm_groc)
groclist_list.grid()

####################################################################
tabControl.add(tab_recipes,text='Recipes')
tabControl.add(tab_meal,text='Meal Plan')
tabControl.add(tab_grocery,text='Grocery List')

root.mainloop()

