"Solder Pots de Creme":
  "ingredient":
    "white chocolate":
      "oz": !!float |-
        120.0
    "cream":
      "pint": !!float |-
        0.5
    "eggs":
      "large": !!float |-
        3.0
    "food coloring, grey":
      "tsp": !!float |-
        1.0
  "instructions": |-
    Step 1: Make as for a custard.
    Step 2: Add food coloring.
"Terra(Dennie)misu":
  "ingredient":
    "cake":
      "cups": !!float |-
        3.0
    "whipped cream":
      "tbs": !!float |-
        7.0
  "instructions": |-
    Step 1: Bake and add butter.
"Root Cause Vegetables":
  "ingredient":
    "potatoes":
      "ea": !!float |-
        6.0
    "rutabaga":
      "ea": !!float |-
        2.0
    "carrots":
      "ea": !!float |-
        5.0
  "instructions": |-
    Step 1: Roast veggies
'Rich Meltn Sandwich':
  "ingredient":
    "bread":
      "lb": !!float |-
        5.0
    "cheese":
      "bottle": !!float |-
        0.25
  "instructions": |-
    Make grilled cheese sandwich.    
"5 WHeY Pancakes":
  "ingredient":
    "whey":
      "cups": !!float |-
        1.0
    "flour":
      "cups": !!float |-
        2
    "baking soda":
      "tsp": !!float |-
        2.0 
  "instructions": |-
    Mix together and make 5 pancakes on a griddle.
"5 WHYs Cream":
  "ingredient":
    "chocolate ice cream":
      "cups": !!float |-
        1.0
    "strawberry ice cream":
      "cups": !!float |-
        1.0
    "vanilla ice cream":
      "cups": !!float |-
        1.0 
    "lemon ice cream":
      "cups": !!float |-
        1.0 
    "cookies and cream ice cream":
      "cups": !!float |-
        1.0         
  "instructions": |-
    Freeze into a layered ice cream dome.
"Paul Salsa-kov":
  "ingredient":
    "tomatoes":
      "lb": !!float |-
        1.0
    "onion":
      "ea": !!float |-
        0.25
    "jalapeno":
      "ea": !!float |-
        1
    "cilantro, chopped":
      "cup": !!float |-
        0.125
  "instructions": |-
    Chop it all up. Eat with chips.
"Eric Horn-of-Plenty Risotto":
  "ingredient":
    "horn-of-plenty mushroom":
      "ea": !!float |-
       10
    "rice":
      "lbs": !!float |-
        1
    "water":
      "cups": !!float |-
        2
  "instructions": |-
    Make a creamy risotto with mushrooms."Crab Rangoon":"Crab Rangoon":
"Chicken pasta":
  "ingredient":
    "chicken breast":
      "lbs.": !!float |-
        0.56
    "pasta":
      "package": !!float |-
        1.0
  "instructions": |-
    Bake chicken. Don't overcook, but make it tasty.

    Mix with pasta.
